#Clientes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientes1
spec:
  selector:
    matchLabels:
      app: clientes1
      role: clientes
      tier: frontend 
  replicas: 1 
  template:
    metadata:
      labels:
        app: clientes1
        role: clientes
        tier: frontend
    spec:
      containers:
        - name: clientes1
          image: albertoseijo/aos_grupo4_global:aos_servicioclientes
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#Vehiculos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiculos2
spec:
  selector:
    matchLabels:
      app: vehiculos2
      role: vehiculos
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: vehiculos2
        role: vehiculos
        tier: frontend
    spec:
      containers:
        - name: vehiculos2
          image: albertoseijo/aos_grupo4_global:serviciovehiculos
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080


---
#TRABAJOS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trabajos3
spec:
  selector:
    matchLabels:
      app: trabajos3
      role: trabajos
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: trabajos3
        role: trabajos
        tier: frontend
    spec:
      containers:
        - name: trabajos3
          image: albertoseijo/aos_grupo4_global:aos_serviciotrabajos
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#NOTIFICACIONES
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones4
spec:
  selector:
    matchLabels:
      app: notificaciones4
      role: notificaciones
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: notificaciones4
        role: notificaciones
        tier: frontend
    spec:
      containers:
        - name: notificaciones4
          image: albertoseijo/aos_grupo4_global:aos_servicionotificaciones
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#FACTURAS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facturas5
spec:
  selector:
    matchLabels:
      app: facturas5
      role: facturas
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: facturas5
        role: facturas
        tier: frontend
    spec:
      containers:
        - name: facturas5
          image: albertoseijo/aos_grupo4_global:aos_serviciofacturas
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#RECAMBIOS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recambios6
spec:
  selector:
    matchLabels:
      app: recambios6
      role: recambios
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: recambios6
        role: recambios
        tier: frontend
    spec:
      containers:
        - name: recambios6
          image: albertoseijo/aos_grupo4_global:aos_serviciorecambios
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#LOGS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs7
spec:
  selector:
    matchLabels:
      app: logs7
      role: logs
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: logs7
        role: logs
        tier: frontend
    spec:
      containers:
        - name: logs7
          image: albertoseijo/aos_grupo4_global:aos_serviciologs
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080


---

#SERVICES

apiVersion: v1
kind: Service
metadata:
  name: clientes1
  labels:
    app: clientes1
    role: clientes
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: clientes1
    role: clientes
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: vehiculos2
  labels:
    app: vehiculos2
    role: vehiculos
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: vehiculos2
    role: vehiculos
    tier: frontend


---

apiVersion: v1
kind: Service
metadata:
  name: trabajos3
  labels:
    app: trabajos3
    role: trabajos
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8080
  selector:
    app: trabajos3
    role: trabajos
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: notificaciones4
  labels:
    app: notificaciones4
    role: notificaciones
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8080
  selector:
    app: notificaciones4
    role: notificaciones
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: facturas5
  labels:
    app: facturas5
    role: facturas
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8080
  selector:
    app: facturas5
    role: facturas
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: recambios6
  labels:
    app: recambios6
    role: recambios
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8080
  selector:
    app: recambios6
    role: recambios
    tier: frontend

---    

apiVersion: v1
kind: Service
metadata:
  name: logs7
  labels:
    app: logs7
    role: recambios
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8087
      targetPort: 8080
  selector:
    app: logs7
    role: logs
    tier: frontend
