#Clientes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientes_1
spec:
  selector:
    matchLabels:
      app: clientes_1
      role: clientes
      tier: frontend 
  replicas: 1 
  template:
    metadata:
      labels:
        app: clientes_1
        role: clientes
        tier: frontend
    spec:
      containers:
        - name: clientes_1
          image: albertoseijo/aos_grupo4_global:aos_servicioclientes
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#Vehiculos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiculos_2
spec:
  selector:
    matchLabels:
      app: vehiculos_2
      role: vehiculos
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: vehiculos_2
        role: vehiculos
        tier: frontend
    spec:
      containers:
        - name: vehiculos_2
          image: albertoseijo/aos_grupo4_global:serviciovehiculos
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080


---
#TRABAJOS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trabajos_3
spec:
  selector:
    matchLabels:
      app: trabajos_3
      role: trabajos
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: trabajos_3
        role: trabajos
        tier: frontend
    spec:
      containers:
        - name: trabajos_3
          image: albertoseijo/aos_grupo4_global:aos_serviciotrabajos
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#NOTIFICACIONES
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones_4
spec:
  selector:
    matchLabels:
      app: notificaciones_4
      role: notificaciones
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: notificaciones_4
        role: notificaciones
        tier: frontend
    spec:
      containers:
        - name: notificaciones_4
          image: albertoseijo/aos_grupo4_global:aos_servicionotificaciones
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#FACTURAS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facturas_5
spec:
  selector:
    matchLabels:
      app: facturas_5
      role: facturas
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: facturas_5
        role: facturas
        tier: frontend
    spec:
      containers:
        - name: facturas_5
          image: albertoseijo/aos_grupo4_global:aos_serviciofacturas
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#RECAMBIOS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recambios_6
spec:
  selector:
    matchLabels:
      app: recambios_6
      role: recambios
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: recambios_6
        role: recambios
        tier: frontend
    spec:
      containers:
        - name: recambios_6
          image: albertoseijo/aos_grupo4_global:aos_serviciorecambios
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080

---

#LOGS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs_7
spec:
  selector:
    matchLabels:
      app: logs_7
      role: logs
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: logs_7
        role: logs
        tier: frontend
    spec:
      containers:
        - name: logs_7
          image: albertoseijo/aos_grupo4_global:aos_serviciologs
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "700Mi"
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8080


---

#SERVICES

apiVersion: v1
kind: Service
metadata:
  name: clientes_1
  labels:
    app: clientes_1
    role: clientes
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: clientes_1
    role: clientes
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: vehiculos_2
  labels:
    app: vehiculos_2
    role: vehiculos
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: vehiculos_2
    role: vehiculos
    tier: frontend


---

apiVersion: v1
kind: Service
metadata:
  name: trabajos_3
  labels:
    app: trabajos_3
    role: trabajos
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8080
  selector:
    app: trabajos_3
    role: trabajos
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: notificaciones_4
  labels:
    app: notificaciones_4
    role: notificaciones
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8080
  selector:
    app: notificaciones_4
    role: notificaciones
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: facturas_5
  labels:
    app: facturas_5
    role: facturas
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8080
  selector:
    app: facturas_5
    role: facturas
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: recambios_6
  labels:
    app: recambios_6
    role: recambios
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8080
  selector:
    app: recambios_6
    role: recambios
    tier: frontend

---    

apiVersion: v1
kind: Service
metadata:
  name: logs_7
  labels:
    app: logs_7
    role: recambios
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8087
      targetPort: 8080
  selector:
    app: logs_7
    role: logs
    tier: frontend
