version: "3"

services:


    clientes_1:
        image: albertoseijo/aos_grupo4_global:aos_servicioclientes
        
        ports:
            - "8081:8080"
        networks:
            - taller_Servicios_Union
    gestion_vehiculos_2:
        image: albertoseijo/aos_grupo4_global:serviciovehiculos
        ports:
            - "8080:8080"
        networks:
            - taller_Servicios_Union
        depends_on:
            - BBDD_gestion_vehiculos_2
    BBDD_gestion_vehiculos_2:
        image: mongo
        restart: always
        networks:
            - taller_Servicios_Union
        environment:
            MONGO_INITDB_DATABASE: ss1
        ports:
            - 27017:27017
        volumes:
            - db_data:/var/lib/mongo

    trabajos_3:
        image: albertoseijo/aos_grupo4_global:aos_serviciotrabajos
        ports:
            - 8083:8080
        networks:
            - taller_Servicios_Union

    notificaciones_4:
        image: albertoseijo/aos_grupo4_global:aos_servicionotificaciones
        ports:
            - 8084:8080
        networks:
            - taller_Servicios_Union

    facturas_5:
        image: albertoseijo/aos_grupo4_global:aos_serviciofacturas
        container_name: api_facturas
        ports:
            - 8085:8080
        networks:
            - taller_Servicios_Union

    recambios_6:
        image: albertoseijo/aos_grupo4_global:aos_serviciorecambios
        ports:
            - 8086:8080
        networks:
            - taller_Servicios_Union  
    logs_7:
        image: albertoseijo/aos_grupo4_global:aos_serviciologs  
        container_name: api_recambios
        ports:
            - 8087:8080
        networks:
            - taller_Servicios_Union            

networks:
    taller_Servicios_Union:

volumes:
    db_data:


