FROM ubuntu:18.04
# LABEL para la imagen
LABEL version="1.0"
LABEL description="Imagen del servicio de Gestion de Notificacion"
# Actualizacion del repositorio de Ubuntu
RUN apt update
# Puerto donde apuntaran los subsistemas
EXPOSE 8084
